<?php

/**
 * BaseHomework
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $lecture_id
 * @property string $filename
 * @property timestamp $date
 * @property integer $rate
 * @property Lecture $Lecture
 * @property sfGuardUser $User
 * 
 * @method integer     getId()         Returns the current record's "id" value
 * @method integer     getUserId()     Returns the current record's "user_id" value
 * @method integer     getLectureId()  Returns the current record's "lecture_id" value
 * @method string      getFilename()   Returns the current record's "filename" value
 * @method timestamp   getDate()       Returns the current record's "date" value
 * @method integer     getRate()       Returns the current record's "rate" value
 * @method Lecture     getLecture()    Returns the current record's "Lecture" value
 * @method sfGuardUser getUser()       Returns the current record's "User" value
 * @method Homework    setId()         Sets the current record's "id" value
 * @method Homework    setUserId()     Sets the current record's "user_id" value
 * @method Homework    setLectureId()  Sets the current record's "lecture_id" value
 * @method Homework    setFilename()   Sets the current record's "filename" value
 * @method Homework    setDate()       Sets the current record's "date" value
 * @method Homework    setRate()       Sets the current record's "rate" value
 * @method Homework    setLecture()    Sets the current record's "Lecture" value
 * @method Homework    setUser()       Sets the current record's "User" value
 * 
 * @package    cukorka
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseHomework extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('homework');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('lecture_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('filename', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '128',
             ));
        $this->hasColumn('date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => '25',
             ));
        $this->hasColumn('rate', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Lecture', array(
             'local' => 'lecture_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}