<?php

/**
 * BaseCourse
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $url
 * @property string $title
 * @property string $description
 * @property Doctrine_Collection $Aids
 * @property Doctrine_Collection $Students
 * @property Doctrine_Collection $Lecturers
 * @property Doctrine_Collection $Lectures
 * @property Doctrine_Collection $CourseStudent
 * @property Doctrine_Collection $CourseLecturer
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getUrl()            Returns the current record's "url" value
 * @method string              getTitle()          Returns the current record's "title" value
 * @method string              getDescription()    Returns the current record's "description" value
 * @method Doctrine_Collection getAids()           Returns the current record's "Aids" collection
 * @method Doctrine_Collection getStudents()       Returns the current record's "Students" collection
 * @method Doctrine_Collection getLecturers()      Returns the current record's "Lecturers" collection
 * @method Doctrine_Collection getLectures()       Returns the current record's "Lectures" collection
 * @method Doctrine_Collection getCourseStudent()  Returns the current record's "CourseStudent" collection
 * @method Doctrine_Collection getCourseLecturer() Returns the current record's "CourseLecturer" collection
 * @method Course              setId()             Sets the current record's "id" value
 * @method Course              setUrl()            Sets the current record's "url" value
 * @method Course              setTitle()          Sets the current record's "title" value
 * @method Course              setDescription()    Sets the current record's "description" value
 * @method Course              setAids()           Sets the current record's "Aids" collection
 * @method Course              setStudents()       Sets the current record's "Students" collection
 * @method Course              setLecturers()      Sets the current record's "Lecturers" collection
 * @method Course              setLectures()       Sets the current record's "Lectures" collection
 * @method Course              setCourseStudent()  Sets the current record's "CourseStudent" collection
 * @method Course              setCourseLecturer() Sets the current record's "CourseLecturer" collection
 * 
 * @package    cukorka
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCourse extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('course');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('url', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '128',
             ));
        $this->hasColumn('title', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '128',
             ));
        $this->hasColumn('description', 'string', 2147483647, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '2147483647',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Aid as Aids', array(
             'local' => 'id',
             'foreign' => 'course_id'));

        $this->hasMany('sfGuardUser as Students', array(
             'refClass' => 'CourseStudent',
             'local' => 'course_id',
             'foreign' => 'student_id'));

        $this->hasMany('sfGuardUser as Lecturers', array(
             'refClass' => 'CourseLecturer',
             'local' => 'course_id',
             'foreign' => 'lecturer_id'));

        $this->hasMany('Lecture as Lectures', array(
             'local' => 'id',
             'foreign' => 'course_id'));

        $this->hasMany('CourseStudent', array(
             'local' => 'id',
             'foreign' => 'course_id'));

        $this->hasMany('CourseLecturer', array(
             'local' => 'id',
             'foreign' => 'course_id'));
    }
}