<?php

/**
 * BaseFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $uploader_id
 * @property integer $lecture_id
 * @property string $file
 * @property timestamp $date
 * 
 * @method integer   getUploaderId()  Returns the current record's "uploader_id" value
 * @method integer   getLectureId()   Returns the current record's "lecture_id" value
 * @method string    getFile()        Returns the current record's "file" value
 * @method timestamp getDate()        Returns the current record's "date" value
 * @method File      setUploaderId()  Sets the current record's "uploader_id" value
 * @method File      setLectureId()   Sets the current record's "lecture_id" value
 * @method File      setFile()        Sets the current record's "file" value
 * @method File      setDate()        Sets the current record's "date" value
 * 
 * @package    cukorka
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('file');
        $this->hasColumn('uploader_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('lecture_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('file', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '128',
             ));
        $this->hasColumn('date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}