<?php

/**
 * BaseProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $full_name
 * @property string $email
 * @property sfGuardUser $User
 * 
 * @method integer     getId()        Returns the current record's "id" value
 * @method integer     getUserId()    Returns the current record's "user_id" value
 * @method string      getFullName()  Returns the current record's "full_name" value
 * @method string      getEmail()     Returns the current record's "email" value
 * @method sfGuardUser getUser()      Returns the current record's "User" value
 * @method Profile     setId()        Sets the current record's "id" value
 * @method Profile     setUserId()    Sets the current record's "user_id" value
 * @method Profile     setFullName()  Sets the current record's "full_name" value
 * @method Profile     setEmail()     Sets the current record's "email" value
 * @method Profile     setUser()      Sets the current record's "User" value
 * 
 * @package    cukorka
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('full_name', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '128',
             ));
        $this->hasColumn('email', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '128',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}