<?php

/**
 * BaseCourseStudent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $course_id
 * @property integer $student_id
 * @property sfGuardUser $sfGuardUser
 * @property Course $Course
 * 
 * @method integer       getCourseId()    Returns the current record's "course_id" value
 * @method integer       getStudentId()   Returns the current record's "student_id" value
 * @method sfGuardUser   getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Course        getCourse()      Returns the current record's "Course" value
 * @method CourseStudent setCourseId()    Sets the current record's "course_id" value
 * @method CourseStudent setStudentId()   Sets the current record's "student_id" value
 * @method CourseStudent setSfGuardUser() Sets the current record's "sfGuardUser" value
 * @method CourseStudent setCourse()      Sets the current record's "Course" value
 * 
 * @package    cukorka
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseCourseStudent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('course_student');
        $this->hasColumn('course_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('student_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'student_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Course', array(
             'local' => 'course_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}