<?php

/**
 * BaseLecture
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $url
 * @property integer $course_id
 * @property string $title
 * @property text $description
 * @property text $homeworktask
 * @property bool $hasHomeworkUploadField
 * @property Course $Course
 * @property Doctrine_Collection $Homeworks
 * 
 * @method integer             getId()                     Returns the current record's "id" value
 * @method string              getUrl()                    Returns the current record's "url" value
 * @method integer             getCourseId()               Returns the current record's "course_id" value
 * @method string              getTitle()                  Returns the current record's "title" value
 * @method text                getDescription()            Returns the current record's "description" value
 * @method text                getHomeworktask()           Returns the current record's "homeworktask" value
 * @method bool                getHasHomeworkUploadField() Returns the current record's "hasHomeworkUploadField" value
 * @method Course              getCourse()                 Returns the current record's "Course" value
 * @method Doctrine_Collection getHomeworks()              Returns the current record's "Homeworks" collection
 * @method Lecture             setId()                     Sets the current record's "id" value
 * @method Lecture             setUrl()                    Sets the current record's "url" value
 * @method Lecture             setCourseId()               Sets the current record's "course_id" value
 * @method Lecture             setTitle()                  Sets the current record's "title" value
 * @method Lecture             setDescription()            Sets the current record's "description" value
 * @method Lecture             setHomeworktask()           Sets the current record's "homeworktask" value
 * @method Lecture             setHasHomeworkUploadField() Sets the current record's "hasHomeworkUploadField" value
 * @method Lecture             setCourse()                 Sets the current record's "Course" value
 * @method Lecture             setHomeworks()              Sets the current record's "Homeworks" collection
 * 
 * @package    cukorka
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseLecture extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lecture');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('url', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '128',
             ));
        $this->hasColumn('course_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('title', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '128',
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('homeworktask', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('hasHomeworkUploadField', 'bool', null, array(
             'type' => 'bool',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Course', array(
             'local' => 'course_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('Homework as Homeworks', array(
             'local' => 'id',
             'foreign' => 'lecture_id'));
    }
}