<?php

/**
 * BaseCourseLecturer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $course_id
 * @property integer $lecturer_id
 * @property sfGuardUser $sfGuardUser
 * @property Course $Course
 * 
 * @method integer        getCourseId()    Returns the current record's "course_id" value
 * @method integer        getLecturerId()  Returns the current record's "lecturer_id" value
 * @method sfGuardUser    getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Course         getCourse()      Returns the current record's "Course" value
 * @method CourseLecturer setCourseId()    Sets the current record's "course_id" value
 * @method CourseLecturer setLecturerId()  Sets the current record's "lecturer_id" value
 * @method CourseLecturer setSfGuardUser() Sets the current record's "sfGuardUser" value
 * @method CourseLecturer setCourse()      Sets the current record's "Course" value
 * 
 * @package    cukorka
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCourseLecturer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('course_lecturer');
        $this->hasColumn('course_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('lecturer_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'lecturer_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Course', array(
             'local' => 'course_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}