<?php

/**
 * BaseHomework
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $rate
 * @property Lecture $Lecture
 * @property sfGuardUser $Uploader
 * 
 * @method integer     getId()       Returns the current record's "id" value
 * @method integer     getRate()     Returns the current record's "rate" value
 * @method Lecture     getLecture()  Returns the current record's "Lecture" value
 * @method sfGuardUser getUploader() Returns the current record's "Uploader" value
 * @method Homework    setId()       Sets the current record's "id" value
 * @method Homework    setRate()     Sets the current record's "rate" value
 * @method Homework    setLecture()  Sets the current record's "Lecture" value
 * @method Homework    setUploader() Sets the current record's "Uploader" value
 * 
 * @package    cukorka
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseHomework extends File
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('homework');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('rate', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Lecture', array(
             'local' => 'lecture_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('sfGuardUser as Uploader', array(
             'local' => 'uploader_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}