<?php

/**
 * Aid
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cukorka
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Aid extends BaseAid
{
    public function construct() {
        $this->type = "aid";
    }

    public static function getFilePath($course_url, $lecture_url, $username , $filename = '') {
        return parent::getFilePath('aid', $course_url, $lecture_url, $username, $filename);
    }

    public function getMyFilePath() {
        return parent::getMyFilePath('aid', $this->file);
    }
}