<?php

/**
 * Course
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    cukorka
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Course extends BaseCourse {
    public function isStudentCheckedIn() {
        $c = Doctrine_Query::create()
                ->from('CheckIn c')
                ->where('c.user_id = ?', sfContext::getInstance()->getUser()->getId())
                ->count();
        return $c != 0;
    }

}