<?php

/**
 * Homework
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    cukorka
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Homework extends BaseHomework {
    /**
     *
     * @param sfGuardUser $User
     * @param Lecture $Lecture
     * @return boolean
     */
    public function hasUserHomework($User, $Lecture) {
        $count = Doctrine_Query::create()
                ->from('homework')
                ->where('user_id = ?' , $User->id)
                ->andWhere('id = ?' , $this->id)
                ->andWhere('lecture_id = ?' , $Lecture->id)
                ->count();
        return $count != 0;
    }

    /**
     *
     * @param Lecture $Lecture
     * @return boolean
     */
    public function hasCurrentUserHomework($Lecture) {
        return $this->hasUserHomework(sfContext::getInstance()->getUser()->getGuardUser(), $Lecture);
    }
}