<?php

/**
 * Lecture
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    cukorka
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Lecture extends BaseLecture {
    /**
     * Returns the current user
     *
     * @return sfGuardUser
     */
    private function getUser() {
        return sfContext::getInstance()->getUser()->getGuardUser();
    }

    /**
     *
     * @return boolean wheter display the form
     */
    public function displayHomeworkForm() {
        if(!$this->getUser())
            return false;

        if($this->displayHomeworkForm === false)
            return false;

        return $this->getUser()->isStudent($this->Course);
    }
}