# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Cukorka.SCH
    description:  Házifeltöltő és motivációs oldal
    keywords:     cukorka, KSZK, Webteam
    language:     hu
    robots:       index, follow

  stylesheets:    [templatemo_style.css]

  javascripts:    []

  has_layout:     true
  layout:         layout
