<?php

/**
 * sfGuardUser
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    cukorka
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser {
/**
 * Get homework associated with the
 *
 * @param Lecture $lecture
 * @return Homework
 */
    public function getHomeworkForLecture($lecture) {
        return Doctrine_Query::create()
        ->from('Homework h')
        ->select('h.*')
        ->where('h.user_id = ?', $this->id)
        ->andWhere('h.lecture_id = ?', $lecture->id)
        ->fetchOne();
    }
}