<?php

/**
 * BasesfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $username
 * @property string $algorithm
 * @property string $salt
 * @property string $password
 * @property boolean $is_active
 * @property boolean $is_super_admin
 * @property timestamp $last_login
 * @property boolean $is_schacc
 * @property Doctrine_Collection $groups
 * @property Doctrine_Collection $permissions
 * @property Doctrine_Collection $sfGuardUserPermission
 * @property Doctrine_Collection $sfGuardUserGroup
 * @property sfGuardRememberKey $RememberKeys
 * @property Doctrine_Collection $Aids
 * @property Doctrine_Collection $CoursesAttend
 * @property Doctrine_Collection $CoursesProfess
 * @property Doctrine_Collection $CourseStudent
 * @property Doctrine_Collection $CourseLecturer
 * @property Doctrine_Collection $Homeworks
 * @property Profile $Profile
 * @property Doctrine_Collection $CheckIns
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getUsername()              Returns the current record's "username" value
 * @method string              getAlgorithm()             Returns the current record's "algorithm" value
 * @method string              getSalt()                  Returns the current record's "salt" value
 * @method string              getPassword()              Returns the current record's "password" value
 * @method boolean             getIsActive()              Returns the current record's "is_active" value
 * @method boolean             getIsSuperAdmin()          Returns the current record's "is_super_admin" value
 * @method timestamp           getLastLogin()             Returns the current record's "last_login" value
 * @method boolean             getIsSchacc()              Returns the current record's "is_schacc" value
 * @method Doctrine_Collection getGroups()                Returns the current record's "groups" collection
 * @method Doctrine_Collection getPermissions()           Returns the current record's "permissions" collection
 * @method Doctrine_Collection getSfGuardUserPermission() Returns the current record's "sfGuardUserPermission" collection
 * @method Doctrine_Collection getSfGuardUserGroup()      Returns the current record's "sfGuardUserGroup" collection
 * @method sfGuardRememberKey  getRememberKeys()          Returns the current record's "RememberKeys" value
 * @method Doctrine_Collection getAids()                  Returns the current record's "Aids" collection
 * @method Doctrine_Collection getCoursesAttend()         Returns the current record's "CoursesAttend" collection
 * @method Doctrine_Collection getCoursesProfess()        Returns the current record's "CoursesProfess" collection
 * @method Doctrine_Collection getCourseStudent()         Returns the current record's "CourseStudent" collection
 * @method Doctrine_Collection getCourseLecturer()        Returns the current record's "CourseLecturer" collection
 * @method Doctrine_Collection getHomeworks()             Returns the current record's "Homeworks" collection
 * @method Profile             getProfile()               Returns the current record's "Profile" value
 * @method Doctrine_Collection getCheckIns()              Returns the current record's "CheckIns" collection
 * @method sfGuardUser         setId()                    Sets the current record's "id" value
 * @method sfGuardUser         setUsername()              Sets the current record's "username" value
 * @method sfGuardUser         setAlgorithm()             Sets the current record's "algorithm" value
 * @method sfGuardUser         setSalt()                  Sets the current record's "salt" value
 * @method sfGuardUser         setPassword()              Sets the current record's "password" value
 * @method sfGuardUser         setIsActive()              Sets the current record's "is_active" value
 * @method sfGuardUser         setIsSuperAdmin()          Sets the current record's "is_super_admin" value
 * @method sfGuardUser         setLastLogin()             Sets the current record's "last_login" value
 * @method sfGuardUser         setIsSchacc()              Sets the current record's "is_schacc" value
 * @method sfGuardUser         setGroups()                Sets the current record's "groups" collection
 * @method sfGuardUser         setPermissions()           Sets the current record's "permissions" collection
 * @method sfGuardUser         setSfGuardUserPermission() Sets the current record's "sfGuardUserPermission" collection
 * @method sfGuardUser         setSfGuardUserGroup()      Sets the current record's "sfGuardUserGroup" collection
 * @method sfGuardUser         setRememberKeys()          Sets the current record's "RememberKeys" value
 * @method sfGuardUser         setAids()                  Sets the current record's "Aids" collection
 * @method sfGuardUser         setCoursesAttend()         Sets the current record's "CoursesAttend" collection
 * @method sfGuardUser         setCoursesProfess()        Sets the current record's "CoursesProfess" collection
 * @method sfGuardUser         setCourseStudent()         Sets the current record's "CourseStudent" collection
 * @method sfGuardUser         setCourseLecturer()        Sets the current record's "CourseLecturer" collection
 * @method sfGuardUser         setHomeworks()             Sets the current record's "Homeworks" collection
 * @method sfGuardUser         setProfile()               Sets the current record's "Profile" value
 * @method sfGuardUser         setCheckIns()              Sets the current record's "CheckIns" collection
 * 
 * @package    cukorka
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BasesfGuardUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('username', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '128',
             ));
        $this->hasColumn('algorithm', 'string', 128, array(
             'type' => 'string',
             'default' => 'sha1',
             'notnull' => true,
             'length' => '128',
             ));
        $this->hasColumn('salt', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('password', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('is_super_admin', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('last_login', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('is_schacc', 'boolean', null, array(
             'type' => 'boolean',
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardGroup as groups', array(
             'refClass' => 'sfGuardUserGroup',
             'local' => 'user_id',
             'foreign' => 'group_id'));

        $this->hasMany('sfGuardPermission as permissions', array(
             'refClass' => 'sfGuardUserPermission',
             'local' => 'user_id',
             'foreign' => 'permission_id'));

        $this->hasMany('sfGuardUserPermission', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardUserGroup', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('sfGuardRememberKey as RememberKeys', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Aid as Aids', array(
             'local' => 'id',
             'foreign' => 'uploader_id'));

        $this->hasMany('Course as CoursesAttend', array(
             'refClass' => 'CourseStudent',
             'local' => 'student_id',
             'foreign' => 'course_id'));

        $this->hasMany('Course as CoursesProfess', array(
             'refClass' => 'CourseLecturer',
             'local' => 'lecturer_id',
             'foreign' => 'course_id'));

        $this->hasMany('CourseStudent', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasMany('CourseLecturer', array(
             'local' => 'id',
             'foreign' => 'lecturer_id'));

        $this->hasMany('Homework as Homeworks', array(
             'local' => 'id',
             'foreign' => 'uploader_id'));

        $this->hasOne('Profile', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('CheckIn as CheckIns', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}