<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/01/28 12:34:50

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=cukorka',
  'username' => 'cukorka',
  'password' => 'cukorka',
  'name' => 'doctrine',
)),);
