<?php
// auto-generated by sfViewConfigHandler
// date: 2010/02/12 01:11:33
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Cukorka.SCH', false, false);
  $response->addMeta('description', 'Házifeltöltő és motivációs oldal', false, false);
  $response->addMeta('keywords', 'cukorka, KSZK, Webteam', false, false);
  $response->addMeta('language', 'hu', false, false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('templatemo_style.css', '', array ());


