Aid:
  tableName: aid
  inheritance:
    extends: File
    type: concrete
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    title:
      type: string(128)
      notnull: true
  relations:
    Lecture:
      local: lecture_id
      foreign: id
      type: one
      foreignType: many
      foreignAlias: Aids
      onDelete: cascade
    sfGuardUser:
      local: uploader_id
      foreign: id
      type: one
      foreignType: many
      alias: Uploader
      foreignAlias: Aids
Course:
  tableName: course
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    url:
      type: string(128)
      notnull: true
      unique: true
    title:
      type: string(128)
      notnull: true
    description:
      type: text
      notnull: true
    check_in_text:
      type: text
      notnull: true
  relations:
    Students:
      class: sfGuardUser
      refClass: CourseStudent
      local: course_id
      foreign: student_id
      foreignAlias: CoursesAttend
    Lecturers:
      class: sfGuardUser
      refClass: CourseLecturer
      local: course_id
      foreign: lecturer_id
      foreignAlias: CoursesProfess
    Lecture:
      local: id
      foreign: course_id
      type: many
      foreignType: one
      alias: Lectures
      foreignAlias: Course
CourseStudent:
  tableName: course_student
  columns:
    course_id:
      type: integer(4)
      primary: true
    student_id:
      type: integer(4)
      primary: true
  relations:
    sfGuardUser:
      local: student_id
      foreign: id
      type: one
      onDelete: cascade
    Course:
      local: course_id
      foreign: id
      type: one
      onDelete: cascade
CourseLecturer:
  tableName: course_lecturer
  columns:
    course_id:
      type: integer(4)
      primary: true
    lecturer_id:
      type: integer(4)
      primary: true
  relations:
    sfGuardUser:
      local: lecturer_id
      foreign: id
      type: one
      onDelete: cascade
    Course:
      local: course_id
      foreign: id
      type: one
      onDelete: cascade
Homework:
  tableName: homework
  inheritance:
    extends: File
    type: concrete
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    rate:
      type: integer(4)
      notnull: false
    comment:
      type: string(128)
      notnull: false
  relations:
    Lecture:
      local: lecture_id
      foreign: id
      type: one
      foreignType: many
      alias: Lecture
      foreignAlias: Homeworks
      onDelete: cascade
    sfGuardUser:
      local: uploader_id
      foreign: id
      type: one
      foreignType: many
      alias: Uploader
      foreignAlias: Homeworks
      onDelete: cascade
Lecture:
  tableName: lecture
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    url:
      type: string(128)
      notnull: true
      unique: true
    course_id:
      type: integer(4)
      notnull: true
    title:
      type: string(128)
      notnull: true
    description:
      type: text
      notnull: true
    homeworktask:
      type: text
    displayHomeworkForm:
      type: boolean
  relations:
    Aid:
      local: id
      foreign: lecture_id
      type: many
      foreignType: one
      alias: Aids
    Course:
      local: course_id
      foreign: id
      type: one
      foreignType: many
      alias: Course
      foreignAlias: Lectures
      onDelete: cascade
Profile:
  tableName: profile
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    user_id:
      type: integer(4)
      notnull: true
    full_name:
      type: string(128)
      notnull: true
    email:
      type: string(128)
      notnull: true
  relations:
    sfGuardUser:
      local: user_id
      foreign: id
      type: one
      foreignType: one
      alias: User
      foreignAlias: Profile
      onDelete: cascade
File:
  abstract: true
  columns:
    uploader_id:
      type: integer(4)
      notnull: true
    lecture_id:
      type: integer(4)
      notnull: true
    file:
      type: string(128)
      notnull: true
    date:
      type: timestamp(25)
      notnull: true
CheckIn:
  tableName: check_in
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    user_id:
      type: integer(4)
      notnull: true
    course_id:
      type: integer(4)
      notnull: true
    motivation:
      type: text
      notnull: ture
    date_of_check_in:
      type: datetime
      notnull: true
  relations:
    sfGuardUser:
      local: user_id
      foreign: id
      type: one
      foreignType: many
      alias: User
      foreignAlias: CheckIns
      onDelete: cascade
    Course:
      local: course_id
      foreign: id
      type: one
      foreignType: many
      alias: Course
      foreignAlias: CheckIns
      onDelete: cascade